/* ============================================================
   FOUR IMAMS — Bilingual Data Module (Sera-compatible format)
   Abu Hanifa (5) + Malik (5) + Al-Shafi'i (5) + Ahmad (5) = 20 stages
   Parallel-field {fieldAr, fieldEn} format matching SEERAH_DB
   ============================================================ */

window.FOUR_IMAMS_DB = {
  "abu-hanifa": {
    labelAr: "الإمام أبو حنيفة النعمان",
    labelEn: "Imam Abu Hanifa Al-Nu'man",
    shortLabelAr: "أبو حنيفة",
    shortLabelEn: "Abu Hanifa",
    titleAr: "إمام المذهب الحنفي",
    titleEn: "Founder of the Hanafi School",
    color: "#C5A84C",
    gradient: "linear-gradient(135deg, #C5A84C, #8B6914)",
    birthAH: "80 AH",
    birthCE: "699 CE",
    deathAH: "150 AH",
    deathCE: "767 CE",
    lifespanAr: "70 سنة",
    lifespanEn: "70 years",
    birthplaceAr: "الكوفة",
    birthplaceEn: "Kufa",
    deathplaceAr: "بغداد",
    deathplaceEn: "Baghdad",
    introAr: "هو النعمان بن ثابت بن زوطي بن ماه التيمي، إمام أهل الرأي، وأحد الأئمة الأربعة عند أهل السنة والجماعة. نشأ في الكوفة وكان يعمل في التجارة قبل أن يتفرغ لطلب العلم. تميز باستخدام القياس والاستحسان في الفقه، وصبر على المحنة حين رفض منصب القضاء.",
    introEn: "Nu'man ibn Thabit, known as Abu Hanifa, was the pioneer of juristic reasoning and one of the four great imams. He grew up in Kufa working as a merchant before dedicating himself to scholarship. He distinguished himself by using analogical reasoning (qiyas) and juristic preference (istihsan) in fiqh, and endured persecution for refusing a judgeship.",
    mapCenter: [32.5, 44.0],
    mapZoom: 6,
    steps: [
      {
        ayah: "",
        ayahRef: "",
        ayahEn: "",
        ayahRefEn: "",
        dateAr: "80 - 100 هـ",
        dateEn: "80 – 100 AH",
        titleAr: "النشأة والتكوين",
        titleEn: "Early Life & Formation",
        mtAr: "الكوفة",
        mtEn: "Kufa",
        mdAr: "ولد النعمان بن ثابت في الكوفة سنة 80 هـ في أسرة فارسية كانت تعمل بالتجارة",
        mdEn: "Abu Hanifa was born in Kufa in 80 AH into a Persian merchant family",
        amb: "day",
        timeAr: "80 - 100 هـ",
        timeEn: "80 – 100 AH",
        distAr: "الكوفة",
        distEn: "Kufa",
        descAr: "ولد النعمان بن ثابت في الكوفة سنة 80 هـ (699 م) في أسرة فارسية كانت تعمل بالتجارة. نشأ في الكوفة التي كانت مركزاً علمياً كبيراً يضم صحابة كراماً وتابعين. تعلم القرآن الكريم والعلوم الأساسية، ثم عمل مع والده في تجارة البز (النسيج). كانت الكوفة في ذلك الوقت تزخر بالعلماء من التابعين الذين أخذوا عن الصحابة، وكان فيها أكثر من 1000 فقيه. تأثر أبو حنيفة بهذا الجو العلمي الخصب. ورغم انشغاله بالتجارة إلا أنه كان يتردد على مجالس العلم.",
        descEn: "Abu Hanifa was born in Kufa in 80 AH (699 CE) into a Persian merchant family. Kufa was a great scholarly center with many Companions and Followers. He learned the Quran and basic sciences, then worked with his father in the textile trade. Kufa at that time was filled with scholars from the Followers who had learned from the Companions, with over 1,000 jurists. Despite his business, Abu Hanifa regularly attended scholarly circles.",
        charsAr: [
          { i: "🎓", n: "عطاء بن أبي رباح", r: "من كبار التابعين، شيخ أبي حنيفة" },
          { i: "📖", n: "نافع مولى ابن عمر", r: "مولى ابن عمر، من كبار المحدثين" },
          { i: "👤", n: "جعفر الصادق", r: "الإمام السادس عند الشيعة، شيخ لأبي حنيفة" }
        ],
        charsEn: [
          { i: "🎓", n: "Ata ibn Abi Rabah", r: "Great Follower, teacher of Abu Hanifa" },
          { i: "📖", n: "Nafi' Mawla Ibn Umar", r: "Client of Ibn Umar, great hadith scholar" },
          { i: "👤", n: "Ja'far al-Sadiq", r: "Sixth Imam, teacher of Abu Hanifa" }
        ],
        lessonAr: "أهمية النشأة في بيئة علمية خصبة • الجمع بين العمل والتجارة وطلب العلم • التأثر بالعلماء والتزود من علومهم",
        lessonEn: "Growing up in a rich scholarly environment • Balancing business and seeking knowledge • Learning from great scholars",
        srcs: ["سير أعلام النبلاء للذهبي (٦/٢٥٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 336, y: 160, scale: 1.0 }
      },
      {
        ayah: "",
        ayahRef: "",
        ayahEn: "",
        ayahRefEn: "",
        dateAr: "100 - 120 هـ",
        dateEn: "100 – 120 AH",
        titleAr: "طلب العلم والتتلمذ",
        titleEn: "Seeking Knowledge",
        mtAr: "الكوفة",
        mtEn: "Kufa",
        mdAr: "اتجه أبو حنيفة إلى علم الكلام أولاً ثم تحول إلى الفقه. تتلمذ على يد حماد بن أبي سليمان لمدة 18 سنة",
        mdEn: "Abu Hanifa first studied theology then turned to fiqh. He studied under Hammad ibn Abi Sulayman for 18 years",
        amb: "day",
        timeAr: "100 - 120 هـ",
        timeEn: "100 – 120 AH",
        distAr: "الكوفة",
        distEn: "Kufa",
        descAr: "بعد أن رأى أبو حنيفة الشيخ حماد بن أبي سليمان في مجلسه، أعجب به وأصبح يلازمه ويخدمه ويتعلم منه. قال أبو حنيفة: 'جلست إلى حماد ثماني عشرة سنة'. توفي حماد سنة 120 هـ، فجلس أبو حنيفة في مجلسه للتدريس والإفتاء. اتجه أبو حنيفة إلى علم الكلام أولاً ثم تحول إلى الفقه. تتلمذ على يد حماد بن أبي سليمان لمدة 18 سنة. لزمه حتى صار أعلم أهل زمانه بالرأي والقياس.",
        descEn: "When Abu Hanifa saw Sheikh Hammad in his circle, he was impressed and began accompanying, serving, and learning from him. Abu Hanifa said: 'I sat with Hammad for eighteen years.' When Hammad died in 120 AH, Abu Hanifa took his place for teaching and issuing fatwas. He first studied theology then turned to fiqh. He studied under Hammad ibn Abi Sulayman for 18 years until he became the most learned of his time in juristic reasoning.",
        charsAr: [
          { i: "🎓", n: "حماد بن أبي سليمان", r: "شيخ أبي حنيفة ومُعلمه الرئيسي (ت 120 هـ)" },
          { i: "👤", n: "عامر الشعبي", r: "من كبار التابعين" },
          { i: "📖", n: "إبراهيم النخعي", r: "فقيه الكوفة الكبير" }
        ],
        charsEn: [
          { i: "🎓", n: "Hammad ibn Abi Sulayman", r: "Abu Hanifa's main teacher (d. 120 AH)" },
          { i: "👤", n: "Amir al-Sha'bi", r: "Great Follower" },
          { i: "📖", n: "Ibrahim al-Nakha'i", r: "Great jurist of Kufa" }
        ],
        lessonAr: "ملازمة الشيخ وخدمته طريق للعلم • طول الصحبة مع العالم تورث العلم الراسخ • الصبر على طلب العلم لسنوات طويلة",
        lessonEn: "Serving a teacher is a path to knowledge • Long companionship with a scholar yields deep knowledge • Patience in seeking knowledge for years",
        srcs: ["سير أعلام النبلاء للذهبي (٦/٢٥٠)", "قصة الإسلام - د. راغب السرجاني"],
        mapFocus: { x: 336, y: 160, scale: 1.0 }
      },
      {
        ayah: "",
        ayahRef: "",
        ayahEn: "",
        ayahRefEn: "",
        dateAr: "120 - 140 هـ",
        dateEn: "120 – 140 AH",
        titleAr: "تأسيس المذهب الحنفي",
        titleEn: "Founding the Hanafi School",
        mtAr: "بغداد / الكوفة",
        mtEn: "Baghdad / Kufa",
        mdAr: "بعد وفاة حماد، جلس أبو حنيفة للتدريس في مسجد الكوفة، واجتمع حوله عدد كبير من طلاب العلم",
        mdEn: "After Hammad's death, Abu Hanifa taught at the Kufa Mosque, attracting many students",
        amb: "day",
        timeAr: "120 - 140 هـ",
        timeEn: "120 – 140 AH",
        distAr: "الكوفة - بغداد",
        distEn: "Kufa – Baghdad",
        descAr: "بعد وفاة حماد، جلس أبو حنيفة للتدريس في مسجد الكوفة، واجتمع حوله عدد كبير من طلاب العلم. وضع أصول المذهب الحنفي الذي يقوم على: الكتاب والسنة، القياس، الاستحسان، الإجماع، والعرف. كان مجلس أبي حنيفة يعج بطلاب العلم، واشتهر بأنه كان يطرح المسائل الفقهية ويناقشها مع تلاميذه قبل أن تنزل بالمسلمين. من تلاميذه الكبار: أبو يوسف ومحمد بن الحسن الشيباني وزفر بن الهذيل. قال الشافعي: 'الناس في الفقه عيال على أبي حنيفة'.",
        descEn: "After Hammad's death, Abu Hanifa taught at the Kufa Mosque, attracting many students. He established the Hanafi school based on: Quran, Sunnah, qiyas, istihsan, ijma', and custom. His circle was full of students. He famously discussed hypothetical fiqh issues with his students before they occurred. His great students included Abu Yusuf, Muhammad al-Shaybani, and Zufar. Al-Shafi'i said: 'People are dependent on Abu Hanifa in fiqh.'",
        charsAr: [
          { i: "📖", n: "أبو يوسف", r: "تلميذ أبي حنيفة، أول قاضي قضاة (ت 182 هـ)" },
          { i: "📖", n: "محمد بن الحسن الشيباني", r: "مدون المذهب الحنفي (ت 189 هـ)" },
          { i: "📖", n: "زفر بن الهذيل", r: "فقيه حنفي كبير (ت 158 هـ)" }
        ],
        charsEn: [
          { i: "📖", n: "Abu Yusuf", r: "Student, first Chief Justice (d. 182 AH)" },
          { i: "📖", n: "Muhammad al-Shaybani", r: "Codifier of Hanafi school (d. 189 AH)" },
          { i: "📖", n: "Zufar ibn al-Hudhayl", r: "Great Hanafi jurist (d. 158 AH)" }
        ],
        lessonAr: "أهمية المنهجية في تأسيس المذاهب الفقهية • استخدام العقل والاجتهاد مع النقل • تخريج تلاميذ أوفياء ينشرون العلم",
        lessonEn: "Methodology is key in founding legal schools • Balancing reason and textual evidence • Graduating loyal students who spread knowledge",
        srcs: ["سير أعلام النبلاء للذهبي (٦/٢٥٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 336, y: 134, scale: 1.0 }
      },
      {
        ayah: "وَلَا تَرْكَنُوا إِلَى الَّذِينَ ظَلَمُوا فَتَمَسَّكُمُ النَّارُ",
        ayahRef: "سورة هود، الآية ١١٣",
        ayahEn: "And do not incline toward those who wrong, lest the Fire touch you.",
        ayahRefEn: "Surah Hud (11), verse 113",
        dateAr: "140 - 150 هـ",
        dateEn: "140 – 150 AH",
        titleAr: "المحنة والاعتقال",
        titleEn: "The Ordeal & Imprisonment",
        mtAr: "بغداد",
        mtEn: "Baghdad",
        mdAr: "عرض عليه الخليفة أبو جعفر المنصور منصب قاضي القضاة فرفض. فغضب المنصور وأمر بسجنه وتعذيبه",
        mdEn: "Caliph al-Mansur offered him chief justice, but he refused. The caliph imprisoned and tortured him",
        amb: "night",
        timeAr: "140 - 150 هـ",
        timeEn: "140 – 150 AH",
        distAr: "بغداد - سجن المنصور",
        distEn: "Baghdad – al-Mansur's Prison",
        descAr: "عرض عليه الخليفة أبو جعفر المنصور منصب قاضي القضاة فرفض. فغضب المنصور وأمر بسجنه وتعذيبه. ضرب بالسياط وأعيد إلى السجن مراراً. ثبت أبو حنيفة على موقفه رافضاً الخضوع لسلطة الخليفة. كان سبب المحنة أن المنصور أراد أن يجعل أبا حنيفة قاضياً للقضاة ليمنح الشرعية لخلافته، لكن أبا حنيفة رفض. سجن وصبر على المحنة. يقال إنه سُمَّ في السجن. توفي سنة 150 هـ شهيداً في السجن.",
        descEn: "Caliph al-Mansur offered Abu Hanifa the position of chief justice, but he refused. The caliph imprisoned and tortured him. He was flogged and imprisoned repeatedly, but remained steadfast. Al-Mansur wanted Abu Hanifa as chief justice to legitimize his caliphate, but Abu Hanifa refused. He was imprisoned and remained patient. It is said he was poisoned in prison. He died in 150 AH as a martyr in prison.",
        charsAr: [
          { i: "👑", n: "أبو جعفر المنصور", r: "الخليفة العباسي" },
          { i: "⚖️", n: "ابن أبي ليلى", r: "قاضي الكوفة" },
          { i: "👤", n: "الحسن بن زياد اللؤلؤي", r: "تلميذه الذي زاره في السجن" }
        ],
        charsEn: [
          { i: "👑", n: "Abu Ja'far al-Mansur", r: "Abbasid Caliph" },
          { i: "⚖️", n: "Ibn Abi Layla", r: "Judge of Kufa" },
          { i: "👤", n: "al-Hasan ibn Ziyad", r: "Student who visited him in prison" }
        ],
        lessonAr: "رفض مناصب السلطان حفاظاً على استقلالية الفتوى • الصبر على المحنة في سبيل المبدأ • «من استغنى عن السلطان استقل»",
        lessonEn: "Refusing positions to maintain juristic independence • Patience in ordeal for principle • 'Who needs not the ruler is truly independent'",
        srcs: ["سير أعلام النبلاء للذهبي (٦/٢٥٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 336, y: 134, scale: 1.0 }
      },
      {
        ayah: "وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا",
        ayahRef: "سورة العنكبوت، الآية ٦٩",
        ayahEn: "And those who strive for Us — We will surely guide them to Our ways.",
        ayahRefEn: "Surah Al-Ankabut (29), verse 69",
        dateAr: "150 هـ",
        dateEn: "150 AH",
        titleAr: "الوفاة والإرث العلمي",
        titleEn: "Death & Legacy",
        mtAr: "بغداد",
        mtEn: "Baghdad",
        mdAr: "توفي الإمام أبو حنيفة في سجن بغداد سنة 150 هـ عن عمر 70 عاماً. ترك إرثاً علمياً هائلاً",
        mdEn: "Abu Hanifa died in a Baghdad prison in 150 AH at age 70. He left a tremendous legacy",
        amb: "day",
        timeAr: "150 هـ",
        timeEn: "150 AH",
        distAr: "بغداد - مقبرة الخيزران",
        distEn: "Baghdad – Khayzuran Cemetery",
        descAr: "توفي الإمام أبو حنيفة في سجن بغداد سنة 150 هـ عن عمر 70 عاماً. ترك إرثاً علمياً هائلاً تمثل في المذهب الحنفي الذي انتشر في العراق وفارس وتركيا والهند والصين، وكان المذهب الرسمي للدولة العثمانية. رغم محنته، انتشر مذهب أبي حنيفة انتشاراً واسعاً بفضل تلاميذه الأوفياء. كان أبو يوسف أول من حمل لواء المذهب حين ولاه هارون الرشيد قضاء القضاة. انتشر المذهب الحنفي في العراق وبلاد الشام وتركيا والبلقان والقوقاز والهند وأفغانستان وبلاد ما وراء النهر والصين.",
        descEn: "Abu Hanifa died in a Baghdad prison in 150 AH at age 70. He left a tremendous legacy — the Hanafi school spread across Iraq, Persia, Turkey, India, and China, becoming the official school of the Ottoman Empire. Despite his ordeal, the Hanafi school spread widely through his loyal students. Abu Yusuf became the first Chief Justice under Harun al-Rashid. The Hanafi school spread across Iraq, Syria, Turkey, the Balkans, the Caucasus, India, Afghanistan, Transoxiana, and China.",
        charsAr: [
          { i: "👑", n: "هارون الرشيد", r: "الخليفة الذي نشر مذهب أبي حنيفة" },
          { i: "📖", n: "أبو يوسف", r: "قاضي القضاة، نشر المذهب" },
          { i: "📖", n: "محمد بن الحسن الشيباني", r: "دون المذهب في كتبه" }
        ],
        charsEn: [
          { i: "👑", n: "Harun al-Rashid", r: "Caliph who promoted the Hanafi school" },
          { i: "📖", n: "Abu Yusuf", r: "Chief Justice, spread the school" },
          { i: "📖", n: "Muhammad al-Shaybani", r: "Codified the school in his books" }
        ],
        lessonAr: "الإخلاص والعلم ينتصران على المحن • العلم إذا أُخلص لله انتشر ولو بعد وفاة صاحبه • صناعة الرجال تلاميذ أوفياء أعظم من صناعة الكتب",
        lessonEn: "Sincerity and knowledge triumph over trials • Sincere knowledge spreads even after death • Raising loyal students is greater than writing books",
        srcs: ["سير أعلام النبلاء للذهبي (٦/٢٥٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 336, y: 134, scale: 1.0 }
      }
    ]
  },

  "malik": {
    labelAr: "الإمام مالك بن أنس",
    labelEn: "Imam Malik ibn Anas",
    shortLabelAr: "مالك",
    shortLabelEn: "Malik",
    titleAr: "إمام دار الهجرة",
    titleEn: "Imam of the Abode of Hijra",
    color: "#1B7A3D",
    gradient: "linear-gradient(135deg, #1B7A3D, #0D4F2B)",
    birthAH: "93 AH",
    birthCE: "711 CE",
    deathAH: "179 AH",
    deathCE: "795 CE",
    lifespanAr: "86 سنة",
    lifespanEn: "86 years",
    birthplaceAr: "المدينة المنورة",
    birthplaceEn: "Medina",
    deathplaceAr: "المدينة المنورة",
    deathplaceEn: "Medina",
    introAr: "هو مالك بن أنس بن مالك بن أبي عامر الأصبحي الحميري، إمام دار الهجرة، وأحد الأئمة الأربعة. عاش في المدينة المنورة طوال حياته، وصنف الموطأ الذي يعد أول كتاب حديث وفقه جامع. تميز مذهبه بالاعتماد على عمل أهل المدينة كمصدر تشريعي.",
    introEn: "Malik ibn Anas, the Imam of Medina, was one of the four great imams. He lived his entire life in Medina and compiled Al-Muwatta, the first comprehensive book of hadith and fiqh. His school relies on the practice of the people of Medina as a legal source.",
    mapCenter: [24.0, 39.0],
    mapZoom: 6,
    steps: [
      {
        ayah: "وَمَن يُؤْتَ الْحِكْمَةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا",
        ayahRef: "سورة البقرة، الآية ٢٦٩",
        ayahEn: "And whoever is given wisdom has been given much good.",
        ayahRefEn: "Surah Al-Baqarah (2), verse 269",
        dateAr: "93 - 120 هـ",
        dateEn: "93 – 120 AH",
        titleAr: "النشأة في المدينة",
        titleEn: "Early Life in Medina",
        mtAr: "المدينة المنورة",
        mtEn: "Medina",
        mdAr: "ولد مالك بن أنس في المدينة المنورة سنة 93 هـ في أسرة عريقة تعود أصولها إلى قبيلة ذي أصبح في اليمن",
        mdEn: "Malik was born in Medina in 93 AH into a noble family originally from Yemen",
        amb: "day",
        timeAr: "93 - 120 هـ",
        timeEn: "93 – 120 AH",
        distAr: "المدينة المنورة",
        distEn: "Medina",
        descAr: "ولد مالك بن أنس في المدينة المنورة سنة 93 هـ (711 م) في أسرة عريقة تعود أصولها إلى قبيلة ذي أصبح في اليمن. نشأ في مدينة رسول الله ﷺ، وتأثر بأجواء العلم والإيمان. كان بيت مالك في المدينة من بيوت العلم والفضل. جده مالك بن أبي عامر صحابي جليل. حفظ مالك القرآن الكريم في سن مبكرة، ثم اتجه إلى حفظ الحديث النبوي.",
        descEn: "Malik was born in Medina in 93 AH (711 CE) into a noble family originally from Yemen. He grew up in the city of the Prophet ﷺ, immersed in an atmosphere of knowledge and faith. Malik's household was one of knowledge and virtue. His grandfather was a noble Companion. Malik memorized the Quran at an early age and then turned to hadith.",
        charsAr: [
          { i: "🎓", n: "ربيعة الرأي", r: "شيخ مالك الأول، فقيه المدينة (ت 136 هـ)" },
          { i: "📖", n: "ابن شهاب الزهري", r: "أول من دون الحديث، شيخ مالك (ت 124 هـ)" },
          { i: "📖", n: "نافع مولى ابن عمر", r: "أثبت التابعين (ت 117 هـ)" }
        ],
        charsEn: [
          { i: "🎓", n: "Rab'iah al-Ra'y", r: "Malik's first teacher (d. 136 AH)" },
          { i: "📖", n: "Ibn Shihab al-Zuhri", r: "First to codify hadith (d. 124 AH)" },
          { i: "📖", n: "Nafi' Mawla Ibn Umar", r: "Most reliable Follower (d. 117 AH)" }
        ],
        lessonAr: "بركة النشأة في المدينة المنورة مدينة العلم • حفظ القرآن في الصغر أساس طلب العلم • الشرف بالعلم لا بالنسب",
        lessonEn: "Blessing of growing up in Medina • Memorizing Quran in childhood is the foundation • Honor comes through knowledge, not lineage",
        srcs: ["سير أعلام النبلاء للذهبي (٨/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 224, y: 310, scale: 1.0 }
      },
      {
        ayah: "إِنَّمَا يَخْشَى اللَّهَ مِنْ عِبَادِهِ الْعُلَمَاءُ",
        ayahRef: "سورة فاطر، الآية ٢٨",
        ayahEn: "Only those among His servants who have knowledge fear Allah.",
        ayahRefEn: "Surah Fatir (35), verse 28",
        dateAr: "120 - 150 هـ",
        dateEn: "120 – 150 AH",
        titleAr: "طلب العلم والتتلمذ",
        titleEn: "Seeking Knowledge",
        mtAr: "المدينة المنورة",
        mtEn: "Medina",
        mdAr: "تتلمذ مالك على يد كبار علماء المدينة، وأبرزهم نافع مولى ابن عمر الذي لزمه 8 سنوات، والزهري",
        mdEn: "Malik studied under Medina's great scholars, especially Nafi' whom he accompanied for 8 years",
        amb: "day",
        timeAr: "120 - 150 هـ",
        timeEn: "120 – 150 AH",
        distAr: "المدينة المنورة",
        distEn: "Medina",
        descAr: "تتلمذ مالك على يد كبار علماء المدينة، وأبرزهم نافع مولى ابن عمر الذي لزمه 8 سنوات، والزهري. صار إمام المدينة في الحديث والفقه بعد وفاة شيوخه. كان مالك شديد التثبت في الحديث، لا يروي إلا عن ثقات. قال: 'لا يؤخذ العلم عن أربعة: سفيه، وصاحب هوى، وكذاب، وشيخ له فضل ولا يعرف ما يحدث'. كان مجلسه في مسجد الرسول ﷺ، يجلس بإجلال ووقار.",
        descEn: "Malik studied under Medina's great scholars, especially Nafi' whom he accompanied for 8 years, and al-Zuhri. He became the leading imam of Medina in hadith and fiqh. Malik was extremely thorough in hadith, only narrating from reliable sources. He said: 'Knowledge is not taken from four: a fool, a person of desires, a liar, and a virtuous elder who does not know what he narrates.' His circle was in the Prophet's Mosque.",
        charsAr: [
          { i: "👤", n: "جعفر الصادق", r: "شيخ مالك، إمام أهل البيت (ت 148 هـ)" },
          { i: "📖", n: "يحيى بن سعيد الأنصاري", r: "شيخ مالك، قاضي المدينة (ت 143 هـ)" },
          { i: "📖", n: "عبد الله بن دينار", r: "من شيوخ مالك العدول (ت 127 هـ)" }
        ],
        charsEn: [
          { i: "👤", n: "Ja'far al-Sadiq", r: "Teacher of Malik (d. 148 AH)" },
          { i: "📖", n: "Yahya al-Ansari", r: "Teacher, judge of Medina (d. 143 AH)" },
          { i: "📖", n: "Abdullah ibn Dinar", r: "Reliable teacher of Malik (d. 127 AH)" }
        ],
        lessonAr: "التثبت في الرواية شرط لقبول الحديث • هيبة العالم تزيد من قدر العلم • مجالس العلم في المساجد أعظمها بركة",
        lessonEn: "Verification is essential for accepting hadith • A scholar's dignity elevates knowledge • Knowledge circles in mosques are most blessed",
        srcs: ["سير أعلام النبلاء للذهبي (٨/٢٠٠)", "قصة الإسلام - د. راغب السرجاني"],
        mapFocus: { x: 224, y: 310, scale: 1.0 }
      },
      {
        ayah: "قُلْ هَلْ يَسْتَوِي الَّذِينَ يَعْلَمُونَ وَالَّذِينَ لَا يَعْلَمُونَ",
        ayahRef: "سورة الزمر، الآية ٩",
        ayahEn: "Say: Are those who know equal to those who do not know?",
        ayahRefEn: "Surah Az-Zumar (39), verse 9",
        dateAr: "150 - 170 هـ",
        dateEn: "150 – 170 AH",
        titleAr: "تأليف الموطأ وتدريس الفقه",
        titleEn: "Writing Al-Muwatta & Teaching",
        mtAr: "المدينة المنورة",
        mtEn: "Medina",
        mdAr: "ألف الإمام مالك كتاب الموطأ، أول كتاب يجمع الحديث النبوي مع فقه الصحابة والتابعين",
        mdEn: "Imam Malik authored Al-Muwatta, the first book combining prophetic hadith with fiqh of Companions",
        amb: "day",
        timeAr: "150 - 170 هـ",
        timeEn: "150 – 170 AH",
        distAr: "المدينة المنورة",
        distEn: "Medina",
        descAr: "ألف الإمام مالك كتاب الموطأ، أول كتاب يجمع الحديث النبوي مع فقه الصحابة والتابعين. عرضه على 70 فقيهاً من فقهاء المدينة فأقروه. استغرق تأليفه 40 سنة. أمر الخليفة أبو جعفر المنصور مالكاً بتأليف كتاب يجمع السنة والفقه فصنع الموطأ. قال مالك: 'عرضت كتابي هذا على سبعين فقيهاً من فقهاء المدينة فكلهم وافقوني عليه'. كان الموطأ أول مدونة فقهية تجمع الحديث والفقه معاً.",
        descEn: "Imam Malik authored Al-Muwatta, the first book combining prophetic hadith with the fiqh of Companions and Followers. He presented it to 70 Medina jurists who approved it. It took 40 years to complete. Caliph al-Mansur asked Malik to compile a book of Sunnah and fiqh, so he wrote Al-Muwatta. Malik said: 'I presented this book to seventy jurists of Medina and they all agreed with it.' It was the first comprehensive legal code.",
        charsAr: [
          { i: "👑", n: "أبو جعفر المنصور", r: "الخليفة الذي طلب تأليف الموطأ" },
          { i: "👑", n: "هارون الرشيد", r: "حضر مجالسه وتأثر به" },
          { i: "📖", n: "عبد الله بن وهب", r: "تلميذه، نشر المذهب في مصر (ت 197 هـ)" }
        ],
        charsEn: [
          { i: "👑", n: "Abu Ja'far al-Mansur", r: "Caliph who requested Al-Muwatta" },
          { i: "👑", n: "Harun al-Rashid", r: "Attended his circles" },
          { i: "📖", n: "Abdullah ibn Wahb", r: "Student who spread the school in Egypt" }
        ],
        lessonAr: "العمل الجماعي والتشاور يثري العلم • التأني في تأليف الكتب (40 سنة للموطأ) • الجمع بين الحديث والفقه في كتاب واحد",
        lessonEn: "Collective work and consultation enrich knowledge • Patience in authoring books (40 years for Al-Muwatta) • Combining hadith and fiqh in one book",
        srcs: ["سير أعلام النبلاء للذهبي (٨/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 224, y: 310, scale: 1.0 }
      },
      {
        ayah: "يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ وَكُونُوا مَعَ الصَّادِقِينَ",
        ayahRef: "سورة التوبة، الآية ١١٩",
        ayahEn: "O you who believe, fear Allah and be with the truthful.",
        ayahRefEn: "Surah At-Tawbah (9), verse 119",
        dateAr: "170 - 179 هـ",
        dateEn: "170 – 179 AH",
        titleAr: "المحنة والجلد",
        titleEn: "The Ordeal & Flogging",
        mtAr: "المدينة المنورة",
        mtEn: "Medina",
        mdAr: "سأله والي المدينة جعفر بن سليمان عن طلاق المكره فأفتى بأنه لا يقع. فغضب الوالي وأمر بجلد مالك",
        mdEn: "The governor asked Malik about coerced divorce. He ruled it invalid. The governor had him flogged",
        amb: "night",
        timeAr: "170 - 179 هـ",
        timeEn: "170 – 179 AH",
        distAr: "المدينة المنورة",
        distEn: "Medina",
        descAr: "سأله والي المدينة جعفر بن سليمان عن طلاق المكره فأفتى بأنه لا يقع. فغضب الوالي وأمر بجلد مالك 70 جلدة حتى انخلع كتفه. صبر مالك واحتسب الأجر عند الله. أفتى مالك بأن الطلاق تحت الإكراه لا يقع، فغضب جعفر بن سليمان لأن هذه الفتوى تعارض مصالحه السياسية. فأمر بجلده. قال عاصم بن عمر: 'جلد مالك بن أنس سبعين سوطاً'. لكن مالكاً عفا عن جعفر وقال: 'إني قد عفوت عنه لله'.",
        descEn: "The governor of Medina asked Malik about coerced divorce. He ruled it invalid. The governor had him flogged 70 lashes until his shoulder was dislocated. Malik bore it patiently for Allah's sake. Malik's fatwa that coerced divorce is invalid angered the governor. Asim ibn Umar said: 'Malik was flogged seventy lashes.' But Malik forgave the governor, saying: 'I have forgiven him for Allah.'",
        charsAr: [
          { i: "👑", n: "جعفر بن سليمان", r: "والٍ على المدينة، أمر بجلد مالك" },
          { i: "👑", n: "الخليفة المهدي", r: "الخليفة في زمن المحنة" },
          { i: "👤", n: "عبد الله بن نافع", r: "تلميذه الذي شهد المحنة" }
        ],
        charsEn: [
          { i: "👑", n: "Ja'far ibn Sulayman", r: "Governor of Medina, ordered flogging" },
          { i: "👑", n: "Caliph al-Mahdi", r: "Caliph during the ordeal" },
          { i: "👤", n: "Abdullah ibn Nafi'", r: "Student who witnessed the ordeal" }
        ],
        lessonAr: "قول الحق ولو كان عليه ضرر • العفو والصفح عن المسيئين • الصبر على البلاء في سبيل العلم",
        lessonEn: "Speaking truth even when it brings harm • Forgiveness and pardon for wrongdoers • Patience in tribulation for knowledge",
        srcs: ["سير أعلام النبلاء للذهبي (٨/٢٠٠)", "قصة الإسلام - د. راغب السرجاني"],
        mapFocus: { x: 224, y: 310, scale: 1.0 }
      },
      {
        ayah: "وَمَا أُوتِيتُم مِّنَ الْعِلْمِ إِلَّا قَلِيلًا",
        ayahRef: "سورة الإسراء، الآية ٨٥",
        ayahEn: "And you have not been given of knowledge except a little.",
        ayahRefEn: "Surah Al-Isra' (17), verse 85",
        dateAr: "179 هـ",
        dateEn: "179 AH",
        titleAr: "الوفاة والإرث",
        titleEn: "Death & Legacy",
        mtAr: "المدينة المنورة",
        mtEn: "Medina",
        mdAr: "توفي الإمام مالك في المدينة المنورة سنة 179 هـ عن عمر 86 سنة. دفن بالبقيع. ترك مذهبه الذي انتشر في الحجاز ومصر وشمال أفريقيا والأندلس",
        mdEn: "Imam Malik died in Medina in 179 AH at age 86, buried in Al-Baqi'. His school spread across Hijaz, Egypt, North Africa, and Andalusia",
        amb: "day",
        timeAr: "179 هـ",
        timeEn: "179 AH",
        distAr: "البقيع - المدينة المنورة",
        distEn: "Al-Baqi' – Medina",
        descAr: "توفي الإمام مالك في المدينة المنورة سنة 179 هـ عن عمر 86 سنة. دفن بالبقيع. ترك مذهبه الذي انتشر في الحجاز ومصر وشمال أفريقيا والأندلس. الموطأ يبقى من أعظم كتب الحديث. مرض مالك ثلاثة أيام ثم توفي. قال الشافعي: 'لقد أصيب به الإسلام بمصيبة عظيمة'. انتشر المذهب المالكي في المدينة ومصر وشمال أفريقيا (تونس، الجزائر، المغرب، ليبيا) والأندلس والسودان وغرب أفريقيا.",
        descEn: "Imam Malik died in Medina in 179 AH at age 86 and was buried in Al-Baqi'. His school spread across Hijaz, Egypt, North Africa, and Andalusia. Al-Muwatta remains among the greatest hadith collections. Malik was ill for three days then died. Al-Shafi'i said: 'Islam has suffered a great calamity.' The Maliki school spread in Medina, Egypt, North Africa, Andalusia, Sudan, and West Africa.",
        charsAr: [
          { i: "📖", n: "الإمام الشافعي", r: "تلميذه، حمل مذهبه إلى مصر" },
          { i: "📖", n: "ابن القاسم", r: "صاحب المدونة، نشر المالكية (ت 191 هـ)" },
          { i: "📖", n: "أشهب بن عبد العزيز", r: "فقيه مالكي في مصر (ت 204 هـ)" }
        ],
        charsEn: [
          { i: "📖", n: "Imam al-Shafi'i", r: "His student, carried his school to Egypt" },
          { i: "📖", n: "Ibn al-Qasim", r: "Author of al-Mudawwana (d. 191 AH)" },
          { i: "📖", n: "Ashhab ibn Abd al-Aziz", r: "Maliki jurist in Egypt (d. 204 AH)" }
        ],
        lessonAr: "خير ما يتركه العالم أتباعه ومذهبه • العلم النافع يمتد أثره بعد الموت • الموطأ - دقة التصنيف وحسن الاختيار",
        lessonEn: "A scholar's best legacy is his followers and school • Beneficial knowledge extends beyond death • Al-Muwatta: precision and excellent selection",
        srcs: ["سير أعلام النبلاء للذهبي (٨/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 224, y: 310, scale: 1.0 }
      }
    ]
  },

  "shafii": {
    labelAr: "الإمام محمد بن إدريس الشافعي",
    labelEn: "Imam Muhammad ibn Idris al-Shafi'i",
    shortLabelAr: "الشافعي",
    shortLabelEn: "Al-Shafi'i",
    titleAr: "ناصر الحديث وإمام المذهب الشافعي",
    titleEn: "Champion of Hadith & Founder of the Shafi'i School",
    color: "#8B2252",
    gradient: "linear-gradient(135deg, #8B2252, #6B1A3E)",
    birthAH: "150 AH",
    birthCE: "767 CE",
    deathAH: "204 AH",
    deathCE: "820 CE",
    lifespanAr: "54 سنة",
    lifespanEn: "54 years",
    birthplaceAr: "غزة - فلسطين",
    birthplaceEn: "Gaza – Palestine",
    deathplaceAr: "مصر - الفسطاط",
    deathplaceEn: "Egypt – Fustat",
    introAr: "هو محمد بن إدريس الشافعي المطلبي القرشي، ناصر الحديث، وإمام المذهب الشافعي. جمع بين مدرستي الحديث والرأي، ويعتبر مؤسس علم أصول الفقه من خلال كتابه 'الرسالة'. ولد في غزة وتنقل بين مكة والمدينة وبغداد ومصر.",
    introEn: "Muhammad ibn Idris al-Shafi'i, the champion of hadith, founded the Shafi'i school. He synthesized the hadith-based and reason-based schools and is considered the founder of usul al-fiqh through his book 'Al-Risalah'. He traveled from Gaza to Mecca, Medina, Baghdad, and Egypt.",
    mapCenter: [27.0, 37.0],
    mapZoom: 5,
    steps: [
      {
        ayah: "وَرَبَّكَ فَكَبِّر",
        ayahRef: "سورة المدثر، الآية ٣",
        ayahEn: "And your Lord magnify.",
        ayahRefEn: "Surah Al-Muddaththir (74), verse 3",
        dateAr: "150 - 170 هـ",
        dateEn: "150 – 170 AH",
        titleAr: "النشأة والتكوين",
        titleEn: "Early Life & Formation",
        mtAr: "غزة - فلسطين",
        mtEn: "Gaza – Palestine",
        mdAr: "ولد الإمام الشافعي في غزة بفلسطين سنة 150 هـ وهي السنة التي توفي فيها الإمام أبو حنيفة",
        mdEn: "Al-Shafi'i was born in Gaza, Palestine in 150 AH, the same year Abu Hanifa died",
        amb: "day",
        timeAr: "150 - 170 هـ",
        timeEn: "150 – 170 AH",
        distAr: "غزة - مكة",
        distEn: "Gaza – Mecca",
        descAr: "ولد الإمام الشافعي في غزة بفلسطين سنة 150 هـ (767 م) وهي السنة التي توفي فيها الإمام أبو حنيفة. توفي والده وهو صغير، فحملته أمه إلى مكة. نشأ في مكة، حفظ القرآن في 7 سنين، وحفظ الموطأ في 10 سنين. نشأ الشافعي يتيماً فقيراً في مكة. كان شديد الذكاء والحفظ. قال: 'كنت ألقط الكاغد من الطرق لأكتب عليه من قلة الشيء'. أذن له شيخه بالفتوى وهو ابن 15 سنة.",
        descEn: "Al-Shafi'i was born in Gaza, Palestine in 150 AH, the same year Abu Hanifa died. His father died young, so his mother took him to Mecca. He memorized the Quran in 7 years and Al-Muwatta in 10 years. Al-Shafi'i grew up a poor orphan in Mecca. He was exceptionally intelligent. He said: 'I would pick up scraps of paper from the streets to write on due to poverty.' His teacher authorized him to give fatwas at 15.",
        charsAr: [
          { i: "🎓", n: "مسلم بن خالد الزنجي", r: "شيخ الشافعي الأول في مكة (ت 179 هـ)" },
          { i: "📖", n: "سفيان بن عيينة", r: "شيخه في الحديث بمكة (ت 198 هـ)" },
          { i: "👤", n: "والدة الشافعي", r: "قامت على تربيته ونقلته إلى مكة" }
        ],
        charsEn: [
          { i: "🎓", n: "Muslim ibn Khalid al-Zanji", r: "Al-Shafi'i's first teacher (d. 179 AH)" },
          { i: "📖", n: "Sufyan ibn Uyaynah", r: "His hadith teacher in Mecca (d. 198 AH)" },
          { i: "👤", n: "Al-Shafi'i's Mother", r: "Raised him and took him to Mecca" }
        ],
        lessonAr: "اليتم والفقر ليسا عائقاً أمام طلب العلم • حفظ القرآن في الصغر أساس التميز • النبوغ المبكر ليس مانعاً من الفتوى",
        lessonEn: "Orphanhood and poverty are no barriers to knowledge • Quran memorization in childhood is the foundation • Early brilliance does not prevent giving fatwa",
        srcs: ["سير أعلام النبلاء للذهبي (١٠/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 96, y: 172, scale: 1.0 }
      },
      {
        ayah: "فَلَوْلَا نَفَرَ مِن كُلِّ فِرْقَةٍ مِّنْهُمْ طَائِفَةٌ لِّيَتَفَقَّهُوا فِي الدِّينِ",
        ayahRef: "سورة التوبة، الآية ١٢٢",
        ayahEn: "Why should not a group from every party go forth to gain understanding in the religion?",
        ayahRefEn: "Surah At-Tawbah (9), verse 122",
        dateAr: "170 - 195 هـ",
        dateEn: "170 – 195 AH",
        titleAr: "طلب العلم - مكة والمدينة",
        titleEn: "Seeking Knowledge – Mecca & Medina",
        mtAr: "المدينة المنورة",
        mtEn: "Medina",
        mdAr: "سافر الشافعي إلى المدينة ليلتقي بالإمام مالك ويأخذ عنه الموطأ. قرأ الموطأ على مالك من حفظه فأعجب به",
        mdEn: "Al-Shafi'i traveled to Medina to study Al-Muwatta with Imam Malik. He recited it from memory, impressing Malik",
        amb: "day",
        timeAr: "170 - 195 هـ",
        timeEn: "170 – 195 AH",
        distAr: "مكة - المدينة - اليمن - بغداد",
        distEn: "Mecca – Medina – Yemen – Baghdad",
        descAr: "سافر الشافعي إلى المدينة ليلتقي بالإمام مالك ويأخذ عنه الموطأ. قرأ الموطأ على مالك من حفظه فأعجب به. ثم سافر إلى اليمن وعمل قاضياً. اتهم بالميل إلى العلويين فاستدعي إلى بغداد. قدم الشافعي المدينة فأتى مجلس مالك بهيبة وخشوع. قرأ عليه الموطأ كله من حفظه. تولى القضاء في نجران باليمن. اتهم بالتشيع فحمل مكبلاً إلى بغداد سنة 184 هـ، لكن هارون الرشيد أطلقه بعد أن تأكد من براءته.",
        descEn: "Al-Shafi'i traveled to Medina to study Al-Muwatta with Imam Malik. He recited it from memory, impressing Malik. He then went to Yemen as a judge. Accused of Alid sympathies, he was summoned to Baghdad. He came to Medina and sat in Malik's circle with awe. He recited all of Al-Muwatta from memory. He became a judge in Najran, Yemen. Accused of Shi'ism, he was brought in chains to Baghdad in 184 AH, but Harun al-Rashid freed him.",
        charsAr: [
          { i: "🎓", n: "الإمام مالك بن أنس", r: "شيخه في المدينة (ت 179 هـ)" },
          { i: "👑", n: "هارون الرشيد", r: "الخليفة الذي أنصفه وأطلقه" },
          { i: "📖", n: "محمد بن الحسن الشيباني", r: "ناظره في بغداد" }
        ],
        charsEn: [
          { i: "🎓", n: "Imam Malik", r: "His teacher in Medina (d. 179 AH)" },
          { i: "👑", n: "Harun al-Rashid", r: "Caliph who exonerated him" },
          { i: "📖", n: "Muhammad al-Shaybani", r: "His debate partner in Baghdad" }
        ],
        lessonAr: "الرحلة في طلب العلم سبيل العظماء • حفظ المتون قبل لقاء الشيوخ • العلم ينقذ صاحبه من التهم",
        lessonEn: "Traveling for knowledge is the path of the great • Memorizing texts before meeting teachers • Knowledge saves its possessor from accusations",
        srcs: ["سير أعلام النبلاء للذهبي (١٠/٢٠٠)", "قصة الإسلام - د. راغب السرجاني"],
        mapFocus: { x: 224, y: 310, scale: 1.0 }
      },
      {
        ayah: "وَمَن لَّمْ يَجْعَلِ اللَّهُ لَهُ نُورًا فَمَا لَهُ مِن نُّورٍ",
        ayahRef: "سورة النور، الآية ٤٠",
        ayahEn: "And whoever Allah does not grant light — for him there is no light.",
        ayahRefEn: "Surah An-Nur (24), verse 40",
        dateAr: "195 - 199 هـ",
        dateEn: "195 – 199 AH",
        titleAr: "في بغداد - المذهب القديم",
        titleEn: "In Baghdad – The Old School",
        mtAr: "بغداد",
        mtEn: "Baghdad",
        mdAr: "استقر الشافعي في بغداد وناظر فقهاء الحنفية، واجتمع بأحمد بن حنبل. وضع أول كتاب له في أصول الفقه 'الرسالة'",
        mdEn: "Al-Shafi'i settled in Baghdad, debating Hanafi jurists and meeting Ahmad ibn Hanbal. He wrote 'Al-Risalah'",
        amb: "day",
        timeAr: "195 - 199 هـ",
        timeEn: "195 – 199 AH",
        distAr: "بغداد",
        distEn: "Baghdad",
        descAr: "استقر الشافعي في بغداد وناظر فقهاء الحنفية، واجتمع بأحمد بن حنبل. وضع أول كتاب له في أصول الفقه 'الرسالة' وأملى مذهبه القديم. في بغداد جمع الشافعي بين مدرسة الحديث ومدرسة الرأي. جلس في مجلس محمد بن الحسن الشيباني وقرأ كتبه. قال الشافعي: 'ما ناظرني أحد إلا رحمته إلا محمد بن الحسن'. حضر مجالسه أحمد بن حنبل وقال: 'ما رأيت أحداً أفقه في كتاب الله من الشافعي'.",
        descEn: "Al-Shafi'i settled in Baghdad, debating Hanafi jurists and meeting Ahmad ibn Hanbal. He wrote his first usul al-fiqh work 'Al-Risalah' and dictated his old school. In Baghdad, al-Shafi'i synthesized the hadith and reason schools. He sat with Muhammad al-Shaybani and studied his books. Ahmad ibn Hanbal attended his circles and said: 'I have not seen anyone more knowledgeable of Allah's Book than al-Shafi'i.'",
        charsAr: [
          { i: "📖", n: "الإمام أحمد بن حنبل", r: "تلميذه في بغداد (ت 241 هـ)" },
          { i: "📖", n: "محمد بن الحسن الشيباني", r: "نظيره ومناظره (ت 189 هـ)" },
          { i: "👤", n: "الحسن بن محمد الصباح", r: "تلميذه الزاهد في بغداد" }
        ],
        charsEn: [
          { i: "📖", n: "Imam Ahmad ibn Hanbal", r: "His student in Baghdad (d. 241 AH)" },
          { i: "📖", n: "Muhammad al-Shaybani", r: "His peer and debate partner (d. 189 AH)" },
          { i: "👤", n: "al-Hasan ibn Muhammad", r: "His ascetic student in Baghdad" }
        ],
        lessonAr: "الانفتاح على المدارس الأخرى يثري العلم • المناظرة بالحسنى تزيد العلم وضوحاً • الجمع بين مدرستي الحديث والرأي عبقرية فقهية",
        lessonEn: "Openness to other schools enriches knowledge • Civil debate clarifies knowledge • Synthesizing hadith and reason is juristic genius",
        srcs: ["سير أعلام النبلاء للذهبي (١٠/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 336, y: 134, scale: 1.0 }
      },
      {
        ayah: "رَبِّ زِدْنِي عِلْمًا",
        ayahRef: "سورة طه، الآية ١١٤",
        ayahEn: "My Lord, increase me in knowledge.",
        ayahRefEn: "Surah Ta-Ha (20), verse 114",
        dateAr: "199 - 204 هـ",
        dateEn: "199 – 204 AH",
        titleAr: "في مصر - المذهب الجديد",
        titleEn: "In Egypt – The New School",
        mtAr: "الفسطاط - مصر",
        mtEn: "Fustat – Egypt",
        mdAr: "انتقل الشافعي إلى مصر سنة 199 هـ واستقر في الفسطاط. هنا أعاد صياغة مذهبه (المذهب الجديد)",
        mdEn: "Al-Shafi'i moved to Egypt in 199 AH and settled in Fustat. Here he reformulated his school (the New School)",
        amb: "day",
        timeAr: "199 - 204 هـ",
        timeEn: "199 – 204 AH",
        distAr: "الفسطاط - مصر",
        distEn: "Fustat – Egypt",
        descAr: "انتقل الشافعي إلى مصر سنة 199 هـ واستقر في الفسطاط. هنا أعاد صياغة مذهبه (المذهب الجديد). أملى كتبه على تلاميذه ومن أهمها 'الأم' و'الرسالة'. استقبله المصريون استقبالاً حافلاً. قال: 'أصحابي في مصر أفضل من أصحابي في بغداد'. في مصر تحول مذهبه تماماً (القول الجديد) حيث تغيرت بعض الأحكام باختلاف البيئة. أملى كتبه الجديدة على الربيع والمزني.",
        descEn: "Al-Shafi'i moved to Egypt in 199 AH and settled in Fustat. Here he reformulated his school (the New School). He dictated his books to students, including 'Al-Umm' and 'Al-Risalah'. Egyptians gave him a grand welcome. He said: 'My students in Egypt are better than my students in Baghdad.' In Egypt, his school transformed completely (the New Doctrine) as some rulings changed with the new environment.",
        charsAr: [
          { i: "📖", n: "الربيع بن سليمان المرادي", r: "تلميذه الرئيسي وراوي كتبه (ت 270 هـ)" },
          { i: "📖", n: "المزني", r: "تلميذه، صاحب المختصر (ت 264 هـ)" },
          { i: "📖", n: "عبد الله بن وهب", r: "فقيه مصر (ت 197 هـ)" }
        ],
        charsEn: [
          { i: "📖", n: "Al-Rabi' ibn Sulayman", r: "Main student, transmitter (d. 270 AH)" },
          { i: "📖", n: "Al-Muzani", r: "Student, author of Mukhtasar (d. 264 AH)" },
          { i: "📖", n: "Abdullah ibn Wahb", r: "Jurist of Egypt (d. 197 AH)" }
        ],
        lessonAr: "اجتهاد العالم يتغير بتغير البيئة والزمان • المذهب الجديد دليل على مرونة الاجتهاد • أهمية تسجيل العلم في الكتب",
        lessonEn: "A scholar's ijtihad changes with time and place • The New School shows flexibility in ijtihad • Importance of recording knowledge in books",
        srcs: ["سير أعلام النبلاء للذهبي (١٠/٢٠٠)", "قصة الإسلام - د. راغب السرجاني"],
        mapFocus: { x: 28, y: 200, scale: 1.0 }
      },
      {
        ayah: "كُلُّ مَنْ عَلَيْهَا فَانٍ",
        ayahRef: "سورة الرحمن، الآية ٢٦",
        ayahEn: "Everyone upon the earth will perish.",
        ayahRefEn: "Surah Ar-Rahman (55), verse 26",
        dateAr: "204 هـ",
        dateEn: "204 AH",
        titleAr: "الوفاة والإرث",
        titleEn: "Death & Legacy",
        mtAr: "الفسطاط - مصر",
        mtEn: "Fustat – Egypt",
        mdAr: "توفي الإمام الشافعي في مصر سنة 204 هـ عن عمر 54 سنة. دفن في الفسطاط. ترك مذهبه الذي انتشر في مصر والشام والحجاز والعراق وشرق أفريقيا",
        mdEn: "Imam al-Shafi'i died in Egypt in 204 AH at age 54, buried in Fustat. His school spread across Egypt, the Levant, Hijaz, Iraq, and East Africa",
        amb: "day",
        timeAr: "204 هـ",
        timeEn: "204 AH",
        distAr: "الفسطاط - مصر",
        distEn: "Fustat – Egypt",
        descAr: "توفي الإمام الشافعي في مصر سنة 204 هـ عن عمر 54 سنة. دفن في الفسطاط. ترك مذهبه الذي انتشر في مصر والشام والحجاز والعراق وشرق أفريقيا وجنوب شرق آسيا. مرض الشافعي في بطنه. توفي في آخر يوم من شهر رجب سنة 204 هـ. قال المزني: 'دخلت على الشافعي في مرضه فقلت: كيف أصبحت؟ قال: أصبحت من الدنيا راحلاً'. انتشر مذهبه في مصر والشام والحجاز والعراق وخراسان واليمن وشرق أفريقيا وإندونيسيا وماليزيا.",
        descEn: "Imam al-Shafi'i died in Egypt in 204 AH at age 54 and was buried in Fustat. His school spread across Egypt, the Levant, Hijaz, Iraq, East Africa, and Southeast Asia. Al-Shafi'i suffered from a stomach illness. He died on the last day of Rajab 204 AH. Al-Muzani said: 'I visited al-Shafi'i during his illness. He said: I have become a traveler leaving this world.' His school spread across the Muslim world.",
        charsAr: [
          { i: "📖", n: "البويطي", r: "تلميذه، خلفه في حلقة العلم (ت 231 هـ)" },
          { i: "📖", n: "حرملة بن يحيى", r: "تلميذه، راوي مذهبه (ت 243 هـ)" },
          { i: "📖", n: "الربيع بن سليمان الجيزي", r: "تلميذه، روى عنه الأم" }
        ],
        charsEn: [
          { i: "📖", n: "Al-Buwayti", r: "Student who succeeded him (d. 231 AH)" },
          { i: "📖", n: "Harmalah ibn Yahya", r: "Student, transmitter (d. 243 AH)" },
          { i: "📖", n: "Al-Rabi' al-Jizi", r: "Student, transmitted Al-Umm" }
        ],
        lessonAr: "الشيء القليل الذي يبقى خير من الكثير الذي يفنى • أصول الفقه علم مستقل أسسه الشافعي • العالم يرحل وعلمه يبقى",
        lessonEn: "A little that remains is better than much that perishes • Usul al-fiqh was founded by al-Shafi'i • The scholar departs but his knowledge remains",
        srcs: ["سير أعلام النبلاء للذهبي (١٠/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 28, y: 200, scale: 1.0 }
      }
    ]
  },

  "ahmad": {
    labelAr: "الإمام أحمد بن حنبل",
    labelEn: "Imam Ahmad ibn Hanbal",
    shortLabelAr: "أحمد بن حنبل",
    shortLabelEn: "Ahmad ibn Hanbal",
    titleAr: "ناصر السنة وصابر المحنة",
    titleEn: "Defender of the Sunnah & Patient in Tribulation",
    color: "#4A0080",
    gradient: "linear-gradient(135deg, #4A0080, #7B68EE)",
    birthAH: "164 AH",
    birthCE: "780 CE",
    deathAH: "241 AH",
    deathCE: "855 CE",
    lifespanAr: "77 سنة",
    lifespanEn: "77 years",
    birthplaceAr: "بغداد",
    birthplaceEn: "Baghdad",
    deathplaceAr: "بغداد",
    deathplaceEn: "Baghdad",
    introAr: "هو أحمد بن محمد بن حنبل الشيباني، إمام أهل السنة والجماعة، وصاحب المذهب الحنبلي. اشتهر بثباته في محنة خلق القرآن، حيث صبر على السجن والضرب دون أن يتنازل عن عقيدته. صاحب المسند الذي يضم أكثر من 30 ألف حديث.",
    introEn: "Ahmad ibn Muhammad ibn Hanbal, the Imam of Ahl al-Sunnah, founded the Hanbali school. He is famed for his steadfastness during the Inquisition on the createdness of the Quran, enduring imprisonment and flogging without compromising his creed. He compiled Al-Musnad containing over 30,000 hadiths.",
    mapCenter: [33.0, 44.0],
    mapZoom: 6,
    steps: [
      {
        ayah: "وَلَقَدْ يَسَّرْنَا الْقُرْآنَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍ",
        ayahRef: "سورة القمر، الآية ١٧",
        ayahEn: "And We have certainly made the Quran easy to remember — so is there anyone who will remember?",
        ayahRefEn: "Surah Al-Qamar (54), verse 17",
        dateAr: "164 - 180 هـ",
        dateEn: "164 – 180 AH",
        titleAr: "النشأة وطلب العلم",
        titleEn: "Early Life & Education",
        mtAr: "بغداد",
        mtEn: "Baghdad",
        mdAr: "ولد أحمد بن محمد بن حنبل في بغداد سنة 164 هـ. توفي والده وهو صغير، فربته أمه بعناية. بدأ طلب الحديث وهو في سن 15 سنة",
        mdEn: "Ahmad ibn Hanbal was born in Baghdad in 164 AH. His father died young, his mother raised him. He began seeking hadith at 15",
        amb: "day",
        timeAr: "164 - 180 هـ",
        timeEn: "164 – 180 AH",
        distAr: "بغداد",
        distEn: "Baghdad",
        descAr: "ولد أحمد بن محمد بن حنبل في بغداد سنة 164 هـ (780 م). توفي والده وهو صغير، فربته أمه بعناية. بدأ طلب الحديث وهو في سن 15 سنة. تميز بقوة الحفظ والذكاء والورع الشديد. كانت بغداد حاضرة العلم والخلافة. حفظ القرآن الكريم وتعلم العربية. قال: 'ابتدأت بطلب الحديث وأنا ابن خمس عشرة سنة'. أمه شجعته على طلب العلم.",
        descEn: "Ahmad ibn Hanbal was born in Baghdad in 164 AH (780 CE). His father died young, and his mother raised him carefully. He began seeking hadith at 15, distinguished by his strong memory, intelligence, and piety. Baghdad was the capital of knowledge and the caliphate. He memorized the Quran and learned Arabic. He said: 'I began seeking hadith at fifteen.' His mother encouraged him.",
        charsAr: [
          { i: "🎓", n: "يحيى بن سعيد القطان", r: "شيخه في الحديث (ت 198 هـ)" },
          { i: "👤", n: "والدة الإمام أحمد", r: "شجعته على طلب العلم" }
        ],
        charsEn: [
          { i: "🎓", n: "Yahya ibn Sa'id al-Qattan", r: "His hadith teacher (d. 198 AH)" },
          { i: "👤", n: "Ahmad's Mother", r: "Encouraged his pursuit of knowledge" }
        ],
        lessonAr: "دور الأم في تربية العلماء • بداية طلب العلم في سن مبكرة • الحرص على السماع من الشيوخ الثقات",
        lessonEn: "The mother's role in raising scholars • Starting education at a young age • Diligence in learning from reliable teachers",
        srcs: ["سير أعلام النبلاء للذهبي (١١/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 336, y: 134, scale: 1.0 }
      },
      {
        ayah: "وَقُل رَّبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ",
        ayahRef: "سورة الإسراء، الآية ٨٠",
        ayahEn: "And say: My Lord, cause me to enter a sound entrance and to exit a sound exit.",
        ayahRefEn: "Surah Al-Isra' (17), verse 80",
        dateAr: "180 - 204 هـ",
        dateEn: "180 – 204 AH",
        titleAr: "الرحلات في طلب الحديث",
        titleEn: "Travels for Hadith",
        mtAr: "مكة المكرمة",
        mtEn: "Mecca",
        mdAr: "رحل أحمد بن حنبل في طلب الحديث إلى الكوفة والبصرة ومكة والمدينة واليمن والشام. التقى بالشافعي في بغداد وتتلمذ عليه",
        mdEn: "Ahmad traveled widely for hadith to Kufa, Basra, Mecca, Medina, Yemen, and Syria. He met al-Shafi'i in Baghdad",
        amb: "day",
        timeAr: "180 - 204 هـ",
        timeEn: "180 – 204 AH",
        distAr: "بغداد - الكوفة - البصرة - مكة - المدينة - اليمن - الشام",
        distEn: "Baghdad – Kufa – Basra – Mecca – Medina – Yemen – Syria",
        descAr: "رحل أحمد بن حنبل في طلب الحديث إلى الكوفة والبصرة ومكة والمدينة واليمن والشام. التقى بالشافعي في بغداد وتتلمذ عليه. جمع 300 ألف حديث وبدأ في تصنيف المسند. رحل إلى اليمن للقاء عبد الرزاق الصنعاني. تتلمذ على الشافعي في بغداد وصاحبه في رحلة الحج. قال أحمد: 'الشافعي كالشمس للناس'. من شيوخه: سفيان بن عيينة، يحيى بن سعيد القطان، وكيع بن الجراح.",
        descEn: "Ahmad traveled widely for hadith to Kufa, Basra, Mecca, Medina, Yemen, and Syria. He met al-Shafi'i in Baghdad and studied under him. He collected 300,000 hadiths and began compiling Al-Musnad. He traveled to Yemen to meet Abd al-Razzaq al-San'ani. He studied under al-Shafi'i and accompanied him on Hajj. Ahmad said: 'Al-Shafi'i is like the sun to people.' His teachers included Sufyan ibn Uyaynah and Waki' ibn al-Jarrah.",
        charsAr: [
          { i: "📖", n: "عبد الرزاق الصنعاني", r: "شيخه في اليمن (ت 211 هـ)" },
          { i: "🎓", n: "الإمام الشافعي", r: "شيخه في الفقه وأصوله" },
          { i: "📖", n: "وكيع بن الجراح", r: "شيخه في الحديث (ت 197 هـ)" }
        ],
        charsEn: [
          { i: "📖", n: "Abd al-Razzaq al-San'ani", r: "His teacher in Yemen (d. 211 AH)" },
          { i: "🎓", n: "Imam al-Shafi'i", r: "His teacher in fiqh and usul" },
          { i: "📖", n: "Waki' ibn al-Jarrah", r: "His hadith teacher (d. 197 AH)" }
        ],
        lessonAr: "الرحلة في طلب الحديث سنة السلف • تحمل المشاق في سبيل العلم • طلب العلم من شيوخ الأمصار المختلفة",
        lessonEn: "Traveling for hadith is the way of the predecessors • Enduring hardships for knowledge • Learning from teachers of different regions",
        srcs: ["سير أعلام النبلاء للذهبي (١١/٢٠٠)", "قصة الإسلام - د. راغب السرجاني"],
        mapFocus: { x: 229, y: 372, scale: 1.0 }
      },
      {
        ayah: "يُرِيدُونَ لِيُطْفِئُوا نُورَ اللَّهِ بِأَفْوَاهِهِمْ وَاللَّهُ مُتِمُّ نُورِهِ",
        ayahRef: "سورة الصف، الآية ٨",
        ayahEn: "They want to extinguish the light of Allah with their mouths, but Allah will perfect His light.",
        ayahRefEn: "Surah As-Saff (61), verse 8",
        dateAr: "218 - 232 هـ",
        dateEn: "218 – 232 AH",
        titleAr: "المحنة - خلق القرآن",
        titleEn: "The Inquisition – Createdness of Quran",
        mtAr: "بغداد",
        mtEn: "Baghdad",
        mdAr: "في عهد الخليفة المأمون ثم المعتصم، فُرضت عقيدة خلق القرآن. رفض أحمد القول بخلق القرآن، فألقي في السجن. ضرب بالسياط حتى أغمي عليه",
        mdEn: "Under Caliphs al-Ma'mun and al-Mu'tasim, the doctrine of created Quran was enforced. Ahmad refused, was imprisoned and flogged until unconscious",
        amb: "night",
        timeAr: "218 - 232 هـ",
        timeEn: "218 – 232 AH",
        distAr: "بغداد - سجن المطبق",
        distEn: "Baghdad – al-Mutbaq Prison",
        descAr: "في عهد الخليفة المأمون ثم المعتصم، فُرضت عقيدة خلق القرآن. رفض أحمد القول بخلق القرآن، فألقي في السجن. ضرب بالسياط حتى أغمي عليه، وبقي ثابتاً. قال: 'القرآن كلام الله غير مخلوق'. بدأت المحنة سنة 218 هـ. سجن أحمد في بغداد ثم أُحضر مكبلاً إلى المأمون في الرقة، لكن المأمون مات قبل مقابلته. في عهد المعتصم، جُلد أحمد حتى غُشي عليه. كان جلاده شديداً. قال المعتصم: 'ما رأيت مثل هذا الرجل'.",
        descEn: "Under Caliphs al-Ma'mun and al-Mu'tasim, the doctrine that the Quran is created was enforced. Ahmad refused, was imprisoned, and flogged until unconscious, but remained steadfast. He said: 'The Quran is Allah's speech, uncreated.' The ordeal began in 218 AH. Ahmad was imprisoned in Baghdad and brought in chains to al-Ma'mun in Raqqa, but al-Ma'mun died before meeting him. Under al-Mu'tasim, Ahmad was flogged until he lost consciousness. Al-Mu'tasim said: 'I have never seen a man like this.'",
        charsAr: [
          { i: "👑", n: "الخليفة المأمون", r: "بدأ محنة خلق القرآن (ت 218 هـ)" },
          { i: "👑", n: "الخليفة المعتصم", r: "الخليفة الذي جلد أحمد (ت 227 هـ)" },
          { i: "👤", n: "ابن أبي دؤاد", r: "قائد المحنة المعتزلي" }
        ],
        charsEn: [
          { i: "👑", n: "Caliph al-Ma'mun", r: "Started the Inquisition (d. 218 AH)" },
          { i: "👑", n: "Caliph al-Mu'tasim", r: "Caliph who flogged Ahmad (d. 227 AH)" },
          { i: "👤", n: "Ibn Abi Du'ad", r: "Mu'tazili leader of the Inquisition" }
        ],
        lessonAr: "ثبات العقيدة في وجه السيف • الصبر على المحنة حتى النهاية • «المتمسك بسنتي عند فساد أمتي له أجر شهيد»",
        lessonEn: "Steadfastness in faith before the sword • Patience in ordeal until the end • 'One who holds to my Sunnah when the nation is corrupt has the reward of a martyr'",
        srcs: ["سير أعلام النبلاء للذهبي (١١/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 336, y: 134, scale: 1.0 }
      },
      {
        ayah: "وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا",
        ayahRef: "سورة العنكبوت، الآية ٦٩",
        ayahEn: "And those who strive for Us — We will surely guide them to Our ways.",
        ayahRefEn: "Surah Al-Ankabut (29), verse 69",
        dateAr: "232 - 241 هـ",
        dateEn: "232 – 241 AH",
        titleAr: "العودة والازدهار",
        titleEn: "Return & Flourishing",
        mtAr: "بغداد",
        mtEn: "Baghdad",
        mdAr: "تولى الخليفة المتوكل سنة 232 هـ وأوقف المحنة وأكرم أحمد. عاد أحمد إلى التدريس واجتمع حوله الآلاف",
        mdEn: "Caliph al-Mutawakkil ended the Inquisition in 232 AH and honored Ahmad. He returned to teaching with thousands attending",
        amb: "day",
        timeAr: "232 - 241 هـ",
        timeEn: "232 – 241 AH",
        distAr: "بغداد",
        distEn: "Baghdad",
        descAr: "تولى الخليفة المتوكل سنة 232 هـ وأوقف المحنة وأكرم أحمد. عاد أحمد إلى التدريس واجتمع حوله الآلاف. أتم تصنيف المسند. تتلمذ عليه كبار المحدثين كالبخاري ومسلم وأبي داود. بعد المحنة أصبح لأحمد مكانة عظيمة. رفض أن يزور الخليفة قائلاً: 'أنا رجل قد امتحن الله بي'. بلغ عدد من حضروا جنازته أكثر من مليون شخص.",
        descEn: "Caliph al-Mutawakkil ended the Inquisition in 232 AH and honored Ahmad. He returned to teaching, with thousands attending his circles. He completed Al-Musnad. Great muhaddithun like al-Bukhari, Muslim, and Abu Dawud studied under him. After the ordeal, Ahmad attained great status. He refused to visit the caliph, saying: 'I am a man whom Allah has tested.' Over one million people attended his funeral.",
        charsAr: [
          { i: "👑", n: "الخليفة المتوكل", r: "أوقف المحنة (ت 247 هـ)" },
          { i: "📖", n: "الإمام البخاري", r: "تلميذه، صاحب الصحيح (ت 256 هـ)" },
          { i: "📖", n: "الإمام مسلم", r: "تلميذه، صحيح مسلم (ت 261 هـ)" }
        ],
        charsEn: [
          { i: "👑", n: "Caliph al-Mutawakkil", r: "Ended the Inquisition (d. 247 AH)" },
          { i: "📖", n: "Imam al-Bukhari", r: "His student, Sahih al-Bukhari (d. 256 AH)" },
          { i: "📖", n: "Imam Muslim", r: "His student, Sahih Muslim (d. 261 AH)" }
        ],
        lessonAr: "العاقبة للمتقين • رفض الدنيا لا يزيد صاحبها إلا رفعة • تلاميذ أحمد حملوا السنة للأمة",
        lessonEn: "The final outcome is for the righteous • Refusing this world only elevates one's status • Ahmad's students carried the Sunnah to the Ummah",
        srcs: ["سير أعلام النبلاء للذهبي (١١/٢٠٠)", "قصة الإسلام - د. راغب السرجاني"],
        mapFocus: { x: 336, y: 134, scale: 1.0 }
      },
      {
        ayah: "إِنَّ اللَّهَ اشْتَرَى مِنَ الْمُؤْمِنِينَ أَنفُسَهُمْ وَأَمْوَالَهُم بِأَنَّ لَهُمُ الْجَنَّةَ",
        ayahRef: "سورة التوبة، الآية ١١١",
        ayahEn: "Allah has purchased from the believers their lives and their properties — for them is Paradise.",
        ayahRefEn: "Surah At-Tawbah (9), verse 111",
        dateAr: "241 هـ",
        dateEn: "241 AH",
        titleAr: "الوفاة والإرث",
        titleEn: "Death & Legacy",
        mtAr: "بغداد",
        mtEn: "Baghdad",
        mdAr: "توفي الإمام أحمد بن حنبل في بغداد سنة 241 هـ عن عمر 77 سنة. حضر جنازته ما يقدر بمليون شخص",
        mdEn: "Imam Ahmad ibn Hanbal died in Baghdad in 241 AH at age 77. His funeral was attended by an estimated one million people",
        amb: "day",
        timeAr: "241 هـ",
        timeEn: "241 AH",
        distAr: "بغداد - مقبرة باب حرب",
        distEn: "Baghdad – Bab Harb Cemetery",
        descAr: "توفي الإمام أحمد بن حنبل في بغداد سنة 241 هـ عن عمر 77 سنة. حضر جنازته ما يقدر بمليون شخص. ترك مذهبه الذي ينتشر في السعودية وقطر وبعض دول الخليج. المسند يعد من أعظم كتب الحديث. مرض أحمد أياماً وتوفي يوم الجمعة 12 ربيع الأول سنة 241 هـ. قال المؤرخون: 'شهد جنازته ما بين مليون إلى مليون وثلثمائة ألف'. دفن في مقبرة باب حرب ببغداد. ترك المذهب الحنبلي الذي يتميز بالتمسك بالنصوص.",
        descEn: "Imam Ahmad ibn Hanbal died in Baghdad in 241 AH at age 77. His funeral was attended by an estimated one million people. His school is followed in Saudi Arabia, Qatar, and parts of the Gulf. Al-Musnad is among the greatest hadith collections. He was ill for days and died on Friday, 12 Rabi' al-Awwal 241 AH. Historians said: 'Between one million and one million three hundred thousand attended his funeral.' He was buried in Baghdad's Bab Harb cemetery.",
        charsAr: [
          { i: "📖", n: "عبد الله بن أحمد", r: "ابنه وتلميذه، روى المسند (ت 290 هـ)" },
          { i: "📖", n: "أبو داود السجستاني", r: "تلميذه، صاحب السنن (ت 275 هـ)" }
        ],
        charsEn: [
          { i: "📖", n: "Abdullah ibn Ahmad", r: "His son, transmitted Al-Musnad (d. 290 AH)" },
          { i: "📖", n: "Abu Dawud al-Sijistani", r: "His student, Sunan Abi Dawud (d. 275 AH)" }
        ],
        lessonAr: "من يعش لله يرفعه الله في الدنيا والآخرة • المسند أضخم كتب الحديث النبوي • حب الناس ليس دليلاً على الحق، لكنه بركة",
        lessonEn: "Who lives for Allah is raised by Him in this world and the next • Al-Musnad is the largest hadith collection • People's love is not proof of truth, but a blessing",
        srcs: ["سير أعلام النبلاء للذهبي (١١/٢٠٠)", "قصة الإسلام - د. راغب السرجاني", "د. علي الصلابي"],
        mapFocus: { x: 336, y: 134, scale: 1.0 }
      }
    ]
  }
};
